spring.application.name=DemoFullStack
#Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
# ${POSTGRES_USERNAME}
spring.datasource.username=${POSTGRES_USERNAME}
# ${POSTGRES_PASSWORD}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#show sql in console (for debugging)
spring.sql.init.mode=always